# Mosquitto configuration file


# Default listener
listener 1883
protocol mqtt

# websocket listener
listener 9001
protocol websockets


################# SSL ##############

# listener 8883
# protocol mqtt

# cafile /etc/ssl/certs/ca-certificates.crt
# keyfile /mosquitto/certs/tls.key
# certfile /mosquitto/certs/tls.crt

# persistence
persistence true
persistence_location /mosquitto/data/

# log settings
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_timestamp true
log_type error
log_type warning
log_type notice
log_type information
log_type websockets

# security
allow_anonymous false
password_file /mosquitto/config/password-init-file

# load dynamic security plugin
plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/dynamic_config/dynamic-security.json
plugin_opt_password_init_file /mosquitto/config/password-init-file